{% set name = "rope" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rope-{{ version }}.tar.gz
  sha256: ac0cbdcda5a546e1e56c54976df07ea2cb04c806f65459bc213536c5d1bc073e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - pytoolconfig >=1.2.2

test:
  imports:
    - rope
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-rope/rope
  summary: a python refactoring library...
  dev_url: https://github.com/python-rope/rope
  license: LGPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
