{% set name = "rope" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64e6d747532e1f5c8009ec5aae3e5523a5bcedf516f39a750d57d8ed749d90da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - rope
    - rope.base
    - rope.base.oi
    - rope.base.oi.type_hinting
    - rope.base.oi.type_hinting.providers
    - rope.base.oi.type_hinting.resolvers
    - rope.base.utils
    - rope.contrib
    - rope.refactor
    - rope.refactor.importutils

about:
  home: https://github.com/python-rope/rope
  license_file: COPYING
  license: GPL 2.0
  summary: A python refactoring library
  dev_url: https://github.com/python-rope/rope
  doc_url: https://pypi.python.org/pypi/rope
  doc_source_url: https://github.com/python-rope/rope/tree/master/docs

extra:
  recipe-maintainers:
    - pmlandwehr
    - jjhelmus
