{% set name = "rope" %}
{% set version = "1.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rope-{{ version }}.tar.gz
  sha256: 93a1bb991fbf0426e8d415102d1c092ccc42e826ce9a42c4d61ce53d7786d9d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - pytoolconfig >=1.2.2

test:
  imports:
    - rope
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python-rope/rope
  summary: a python refactoring library...
  dev_url: https://github.com/python-rope/rope
  license: LGPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
